import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { api } from '../lib/api';
import { useTasksStore } from '../store';
import { StatusBadge } from '../components/StatusBadge';
import CompleteTaskModal from '../components/CompleteTaskModal';
import type { Plan, PlanTask } from '../lib/types';
import { TaskStatus } from '../lib/types';
import { formatDate } from '../lib/format';
import {
  Calendar,
  Clock,
  CheckCircle2,
  SkipForward,
  Layers,
  ArrowRight,
  Plus
} from 'lucide-react';

export default function PlanPage() {
  const [plans, setPlans] = useState<Plan[]>([]);
  const [loading, setLoading] = useState(true);
  const [selectedTask, setSelectedTask] = useState<PlanTask | null>(null);
  const [modalOpen, setModalOpen] = useState(false);

  const { completeTask, skipTask } = useTasksStore();

  const loadPlans = async () => {
    setLoading(true);
    try {
      const activePlans = await api.getActivePlans();
      setPlans(activePlans);
    } catch {
      // ignore
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    loadPlans();
  }, []);

  const handleOpenComplete = (task: PlanTask) => {
    setSelectedTask(task);
    setModalOpen(true);
  };

  const handleSkip = async (taskId: string) => {
    if (confirm('Skip this task? Momentum will record this drift signal.')) {
      await skipTask(taskId);
      await loadPlans();
    }
  };

  return (
    <div className="space-y-8 pb-12">
      {/* Header */}
      <div className="flex flex-col gap-2 sm:flex-row sm:items-center sm:justify-between">
        <div>
          <h1 className="text-2xl font-bold tracking-tight text-slate-900 sm:text-3xl">AI Execution Plans</h1>
          <p className="mt-1 text-sm text-slate-500">
            Intelligent task breakdowns generated by Momentum's provider-agnostic engine.
          </p>
        </div>

        <Link
          to="/goals"
          className="inline-flex items-center gap-2 rounded-xl bg-indigo-600 px-4 py-2.5 text-sm font-semibold text-white shadow-xs hover:bg-indigo-700 transition-colors"
        >
          <Plus className="h-4 w-4" />
          Plan Another Goal
        </Link>
      </div>

      {loading ? (
        <div className="flex h-48 items-center justify-center">
          <div className="text-sm font-medium text-slate-400">Loading active plans...</div>
        </div>
      ) : plans.length === 0 ? (
        <div className="flex flex-col items-center justify-center rounded-3xl border border-dashed border-slate-300 bg-white p-12 text-center">
          <div className="flex h-14 w-14 items-center justify-center rounded-2xl bg-indigo-50 text-indigo-600">
            <Layers className="h-7 w-7" />
          </div>
          <h2 className="mt-4 text-lg font-bold text-slate-900">No active plans yet</h2>
          <p className="mt-1 max-w-sm text-xs text-slate-500">
            Create a goal and trigger "Generate AI Plan" to generate realistic, paced execution tasks.
          </p>
          <Link
            to="/goals"
            className="mt-6 inline-flex items-center gap-2 rounded-xl bg-indigo-600 px-5 py-2.5 text-xs font-semibold text-white hover:bg-indigo-700 transition-colors"
          >
            Go to Goals
            <ArrowRight className="h-4 w-4" />
          </Link>
        </div>
      ) : (
        <div className="space-y-8">
          {plans.map((plan) => {
            const completedCount = plan.tasks.filter((t) => t.status === TaskStatus.Completed).length;
            const progress = plan.tasks.length > 0
              ? Math.round((completedCount / plan.tasks.length) * 100)
              : 0;

            return (
              <div
                key={plan.id}
                className="overflow-hidden rounded-3xl border border-slate-200/90 bg-white shadow-xs"
              >
                {/* Plan Header */}
                <div className="border-b border-slate-100 bg-slate-50/60 p-6">
                  <div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between">
                    <div>
                      <div className="flex items-center gap-2">
                        <span className="rounded-lg bg-indigo-100 px-2.5 py-0.5 text-xs font-bold text-indigo-700">
                          Plan v{plan.version}
                        </span>
                        <span className="text-xs text-slate-400">
                          Created {formatDate(plan.createdAt)}
                        </span>
                      </div>
                      <h2 className="mt-2 text-base font-bold text-slate-900">{plan.summary}</h2>
                    </div>

                    {/* Progress */}
                    <div className="sm:w-48">
                      <div className="flex justify-between text-xs font-semibold text-slate-600 mb-1">
                        <span>Progress</span>
                        <span>{progress}% ({completedCount}/{plan.tasks.length})</span>
                      </div>
                      <div className="h-2 w-full overflow-hidden rounded-full bg-slate-200">
                        <div
                          className="h-full rounded-full bg-indigo-600 transition-all duration-500"
                          style={{ width: `${progress}%` }}
                        />
                      </div>
                    </div>
                  </div>
                </div>

                {/* Tasks List */}
                <div className="divide-y divide-slate-100">
                  {plan.tasks.map((task) => {
                    const isCompleted = task.status === TaskStatus.Completed;
                    const isSkipped = task.status === TaskStatus.Skipped;

                    return (
                      <div
                        key={task.id}
                        className={`group flex items-start justify-between gap-4 p-5 transition-colors ${
                          isCompleted ? 'bg-emerald-50/30' : isSkipped ? 'bg-slate-50/70' : 'hover:bg-slate-50/50'
                        }`}
                      >
                        <div className="flex items-start gap-3.5 min-w-0 flex-1">
                          <button
                            type="button"
                            disabled={isCompleted || isSkipped}
                            onClick={() => handleOpenComplete(task)}
                            className={`mt-0.5 flex h-5 w-5 shrink-0 items-center justify-center rounded-md border transition-all ${
                              isCompleted
                                ? 'border-emerald-600 bg-emerald-600 text-white'
                                : isSkipped
                                ? 'border-slate-300 bg-slate-200 text-slate-500'
                                : 'border-slate-300 hover:border-indigo-600 text-transparent'
                            }`}
                          >
                            <CheckCircle2 className="h-3.5 w-3.5" />
                          </button>

                          <div className="min-w-0 flex-1">
                            <div className="flex flex-wrap items-center gap-2">
                              <span className="text-xs font-mono font-semibold text-slate-400">
                                #{task.order}
                              </span>
                              <h3
                                className={`text-sm font-semibold ${
                                  isCompleted
                                    ? 'text-slate-500 line-through'
                                    : isSkipped
                                    ? 'text-slate-400 line-through'
                                    : 'text-slate-900'
                                }`}
                              >
                                {task.title}
                              </h3>
                              <StatusBadge status={task.status} />
                              <span className="rounded-md bg-slate-100 px-2 py-0.5 text-[10px] font-medium text-slate-600 uppercase">
                                {task.category}
                              </span>
                            </div>

                            {task.description && (
                              <p className="mt-1 text-xs text-slate-500">{task.description}</p>
                            )}

                            <div className="mt-2.5 flex items-center gap-4 text-xs text-slate-400">
                              <span className="flex items-center gap-1">
                                <Clock className="h-3.5 w-3.5" />
                                Est: {task.estimatedMinutes}m
                              </span>
                              {task.actualMinutes && (
                                <span className="font-semibold text-emerald-600">
                                  Actual: {task.actualMinutes}m
                                </span>
                              )}
                              <span className="flex items-center gap-1">
                                <Calendar className="h-3.5 w-3.5" />
                                Scheduled: {formatDate(task.scheduledDate)}
                              </span>
                            </div>
                          </div>
                        </div>

                        {/* Actions */}
                        {!isCompleted && !isSkipped && (
                          <div className="flex items-center gap-2 shrink-0">
                            <button
                              type="button"
                              onClick={() => handleOpenComplete(task)}
                              className="rounded-xl bg-emerald-50 px-3 py-1.5 text-xs font-semibold text-emerald-700 hover:bg-emerald-100 transition-colors"
                            >
                              Complete
                            </button>
                            <button
                              type="button"
                              onClick={() => handleSkip(task.id)}
                              className="rounded-lg p-1.5 text-slate-400 hover:bg-slate-100 hover:text-slate-600 transition-colors"
                              title="Skip task"
                            >
                              <SkipForward className="h-4 w-4" />
                            </button>
                          </div>
                        )}
                      </div>
                    );
                  })}
                </div>
              </div>
            );
          })}
        </div>
      )}

      {/* Complete Modal */}
      <CompleteTaskModal
        isOpen={modalOpen}
        task={selectedTask}
        onClose={() => setModalOpen(false)}
        onConfirm={async (taskId, actualMinutes, note) => {
          await completeTask(taskId, actualMinutes, note);
          await loadPlans();
        }}
      />
    </div>
  );
}
