import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { api } from '../lib/api';
import { useTasksStore, useAdaptationStore } from '../store';
import { StatusBadge } from '../components/StatusBadge';
import CompleteTaskModal from '../components/CompleteTaskModal';
import type { Plan, PlanTask, PlanChangeType } from '../lib/types';
import { TaskStatus, PlanChangeTypeNames } from '../lib/types';
import { formatDate } from '../lib/format';
import {
  Calendar,
  Clock,
  CheckCircle2,
  SkipForward,
  Layers,
  ArrowRight,
  Plus,
  Zap,
  RefreshCw,
  Check,
  X,
  TrendingUp,
  Minus,
  GitBranch,
} from 'lucide-react';

const changeTypeIcons: Record<PlanChangeType, typeof Zap> = {
  [0]: Zap,       // NoChange
  [1]: Minus,     // ReducedLoad
  [2]: TrendingUp, // IncreasedChallenge
  [3]: GitBranch,  // TaskBrokenDown
  [4]: RefreshCw,  // Rescheduled
};

const changeTypeColors: Record<PlanChangeType, string> = {
  [0]: 'text-slate-500 bg-slate-100',
  [1]: 'text-amber-600 bg-amber-50',
  [2]: 'text-emerald-600 bg-emerald-50',
  [3]: 'text-indigo-600 bg-indigo-50',
  [4]: 'text-blue-600 bg-blue-50',
};

export default function PlanPage() {
  const [plans, setPlans] = useState<Plan[]>([]);
  const [loading, setLoading] = useState(true);
  const [selectedTask, setSelectedTask] = useState<PlanTask | null>(null);
  const [modalOpen, setModalOpen] = useState(false);
  const [adaptPlanId, setAdaptPlanId] = useState<string | null>(null);
  const [adaptModalOpen, setAdaptModalOpen] = useState(false);
  const [adaptMode, setAdaptMode] = useState<'preview' | 'apply'>('preview');

  const { completeTask, skipTask } = useTasksStore();
  const { changes, loading: adaptLoading, error: adaptError, previewAdaptation, applyAdaptation, clearChanges } = useAdaptationStore();

  const loadPlans = async () => {
    setLoading(true);
    try {
      const activePlans = await api.getActivePlans();
      setPlans(activePlans);
    } catch {
      // ignore
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    loadPlans();
  }, []);

  const handleOpenComplete = (task: PlanTask) => {
    setSelectedTask(task);
    setModalOpen(true);
  };

  const handleSkip = async (taskId: string) => {
    if (confirm('Skip this task? Momentum will record this drift signal.')) {
      await skipTask(taskId);
      await loadPlans();
    }
  };

  const handleAdaptPreview = async (planId: string) => {
    setAdaptPlanId(planId);
    setAdaptMode('preview');
    await previewAdaptation(planId);
    setAdaptModalOpen(true);
  };

  const handleAdaptApply = async () => {
    if (!adaptPlanId) return;
    setAdaptMode('apply');
    const appliedChanges = await applyAdaptation(adaptPlanId);
    if (appliedChanges.length > 0) {
      await loadPlans();
    }
    setAdaptModalOpen(false);
    setAdaptPlanId(null);
    clearChanges();
  };

  const handleAdaptCancel = () => {
    setAdaptModalOpen(false);
    setAdaptPlanId(null);
    clearChanges();
  };

  return (
    <div className="space-y-8 pb-12">
      {/* Header */}
      <div className="flex flex-col gap-2 sm:flex-row sm:items-center sm:justify-between">
        <div>
          <h1 className="text-2xl font-bold tracking-tight text-slate-900 sm:text-3xl">AI Execution Plans</h1>
          <p className="mt-1 text-sm text-slate-500">
            Intelligent task breakdowns generated by Momentum's provider-agnostic engine.
          </p>
        </div>

        <Link
          to="/goals"
          className="inline-flex items-center gap-2 rounded-xl bg-indigo-600 px-4 py-2.5 text-sm font-semibold text-white shadow-xs hover:bg-indigo-700 transition-colors"
        >
          <Plus className="h-4 w-4" />
          Plan Another Goal
        </Link>
      </div>

      {loading ? (
        <div className="flex h-48 items-center justify-center">
          <div className="text-sm font-medium text-slate-400">Loading active plans...</div>
        </div>
      ) : plans.length === 0 ? (
        <div className="flex flex-col items-center justify-center rounded-3xl border border-dashed border-slate-300 bg-white p-12 text-center">
          <div className="flex h-14 w-14 items-center justify-center rounded-2xl bg-indigo-50 text-indigo-600">
            <Layers className="h-7 w-7" />
          </div>
          <h2 className="mt-4 text-lg font-bold text-slate-900">No active plans yet</h2>
          <p className="mt-1 max-w-sm text-xs text-slate-500">
            Create a goal and trigger "Generate AI Plan" to generate realistic, paced execution tasks.
          </p>
          <Link
            to="/goals"
            className="mt-6 inline-flex items-center gap-2 rounded-xl bg-indigo-600 px-5 py-2.5 text-xs font-semibold text-white hover:bg-indigo-700 transition-colors"
          >
            Go to Goals
            <ArrowRight className="h-4 w-4" />
          </Link>
        </div>
      ) : (
        <div className="space-y-8">
          {plans.map((plan) => {
            const completedCount = plan.tasks.filter((t) => t.status === TaskStatus.Completed).length;
            const progress = plan.tasks.length > 0
              ? Math.round((completedCount / plan.tasks.length) * 100)
              : 0;

            const pendingTasks = plan.tasks.filter((t) => t.status === TaskStatus.Pending).length;
            const hasSignals = pendingTasks > 0 && (plan.tasks.some(t => t.status === TaskStatus.Completed || t.status === TaskStatus.Skipped));

            return (
              <div
                key={plan.id}
                className="overflow-hidden rounded-3xl border border-slate-200/90 bg-white shadow-xs"
              >
                {/* Plan Header */}
                <div className="border-b border-slate-100 bg-slate-50/60 p-6">
                  <div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between">
                    <div>
                      <div className="flex items-center gap-2">
                        <span className="rounded-lg bg-indigo-100 px-2.5 py-0.5 text-xs font-bold text-indigo-700">
                          Plan v{plan.version}
                        </span>
                        <span className="text-xs text-slate-400">
                          Created {formatDate(plan.createdAt)}
                        </span>
                      </div>
                      <h2 className="mt-2 text-base font-bold text-slate-900">{plan.summary}</h2>
                    </div>

                    {/* Progress & Adapt Actions */}
                    <div className="flex flex-col sm:flex-row sm:items-center gap-4 w-full sm:w-auto">
                      <div className="sm:w-48 flex-1">
                        <div className="flex justify-between text-xs font-semibold text-slate-600 mb-1">
                          <span>Progress</span>
                          <span>{progress}% ({completedCount}/{plan.tasks.length})</span>
                        </div>
                        <div className="h-2 w-full overflow-hidden rounded-full bg-slate-200">
                          <div
                            className="h-full rounded-full bg-indigo-600 transition-all duration-500"
                            style={{ width: `${progress}%` }}
                          />
                        </div>
                      </div>

                      {hasSignals && (
                        <button
                          type="button"
                          onClick={() => handleAdaptPreview(plan.id)}
                          disabled={adaptLoading}
                          className="inline-flex items-center gap-2 rounded-xl bg-amber-50 hover:bg-amber-100 px-4 py-2 text-sm font-semibold text-amber-700 transition-colors disabled:opacity-50"
                        >
                          <Zap className="h-4 w-4" />
                          Adapt Plan
                        </button>
                      )}
                    </div>
                  </div>
                </div>

                {/* Tasks List */}
                <div className="divide-y divide-slate-100">
                  {plan.tasks.map((task) => {
                    const isCompleted = task.status === TaskStatus.Completed;
                    const isSkipped = task.status === TaskStatus.Skipped;

                    return (
                      <div
                        key={task.id}
                        className={`group flex items-start justify-between gap-4 p-5 transition-colors ${
                          isCompleted ? 'bg-emerald-50/30' : isSkipped ? 'bg-slate-50/70' : 'hover:bg-slate-50/50'
                        }`}
                      >
                        <div className="flex items-start gap-3.5 min-w-0 flex-1">
                          <button
                            type="button"
                            disabled={isCompleted || isSkipped}
                            onClick={() => handleOpenComplete(task)}
                            className={`mt-0.5 flex h-5 w-5 shrink-0 items-center justify-center rounded-md border transition-all ${
                              isCompleted
                                ? 'border-emerald-600 bg-emerald-600 text-white'
                                : isSkipped
                                ? 'border-slate-300 bg-slate-200 text-slate-500'
                                : 'border-slate-300 hover:border-indigo-600 text-transparent'
                            }`}
                          >
                            <CheckCircle2 className="h-3.5 w-3.5" />
                          </button>

                          <div className="min-w-0 flex-1">
                            <div className="flex flex-wrap items-center gap-2">
                              <span className="text-xs font-mono font-semibold text-slate-400">
                                #{task.order}
                              </span>
                              <h3
                                className={`text-sm font-semibold ${
                                  isCompleted
                                    ? 'text-slate-500 line-through'
                                    : isSkipped
                                    ? 'text-slate-400 line-through'
                                    : 'text-slate-900'
                                }`}
                              >
                                {task.title}
                              </h3>
                              <StatusBadge status={task.status} />
                              <span className="rounded-md bg-slate-100 px-2 py-0.5 text-[10px] font-medium text-slate-600 uppercase">
                                {task.category}
                              </span>
                            </div>

                            {task.description && (
                              <p className="mt-1 text-xs text-slate-500">{task.description}</p>
                            )}

                            <div className="mt-2.5 flex items-center gap-4 text-xs text-slate-400">
                              <span className="flex items-center gap-1">
                                <Clock className="h-3.5 w-3.5" />
                                Est: {task.estimatedMinutes}m
                              </span>
                              {task.actualMinutes && (
                                <span className="font-semibold text-emerald-600">
                                  Actual: {task.actualMinutes}m
                                </span>
                              )}
                              <span className="flex items-center gap-1">
                                <Calendar className="h-3.5 w-3.5" />
                                Scheduled: {formatDate(task.scheduledDate)}
                              </span>
                            </div>
                          </div>
                        </div>

                        {/* Actions */}
                        {!isCompleted && !isSkipped && (
                          <div className="flex items-center gap-2 shrink-0">
                            <button
                              type="button"
                              onClick={() => handleOpenComplete(task)}
                              className="rounded-xl bg-emerald-50 px-3 py-1.5 text-xs font-semibold text-emerald-700 hover:bg-emerald-100 transition-colors"
                            >
                              Complete
                            </button>
                            <button
                              type="button"
                              onClick={() => handleSkip(task.id)}
                              className="rounded-lg p-1.5 text-slate-400 hover:bg-slate-100 hover:text-slate-600 transition-colors"
                              title="Skip task"
                            >
                              <SkipForward className="h-4 w-4" />
                            </button>
                          </div>
                        )}
                      </div>
                    );
                  })}
                </div>
              </div>
            );
          })}
        </div>
      )}

      {/* Complete Modal */}
      <CompleteTaskModal
        isOpen={modalOpen}
        task={selectedTask}
        onClose={() => setModalOpen(false)}
        onConfirm={async (taskId, actualMinutes, note) => {
          await completeTask(taskId, actualMinutes, note);
          await loadPlans();
        }}
      />

      {/* Adaptation Modal */}
      {adaptModalOpen && adaptPlanId && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-900/50 backdrop-blur-xs p-4">
          <div className="w-full max-w-2xl rounded-3xl bg-white p-0 shadow-2xl border border-slate-100 overflow-hidden">
            <div className="flex items-center justify-between border-b border-slate-100 p-5">
              <div className="flex items-center gap-3">
                <div className="flex h-10 w-10 items-center justify-center rounded-xl bg-amber-50 text-amber-600">
                  <Zap className="h-5 w-5" />
                </div>
                <div>
                  <h3 className="text-lg font-bold text-slate-900">
                    {adaptMode === 'preview' ? 'Preview Plan Adaptation' : 'Applying Adaptation'}
                  </h3>
                  <p className="text-xs text-slate-500">
                    {adaptMode === 'preview'
                      ? 'Review proposed changes based on your behavioral signals'
                      : 'Updating plan tasks...'}
                  </p>
                </div>
              </div>
              <button
                onClick={handleAdaptCancel}
                disabled={adaptMode === 'apply'}
                className="rounded-lg p-1.5 text-slate-400 hover:bg-slate-100 hover:text-slate-600 transition-colors disabled:opacity-50"
              >
                <X className="h-5 w-5" />
              </button>
            </div>

            <div className="p-5 max-h-[60vh] overflow-y-auto">
              {adaptError && (
                <div className="mb-4 rounded-xl border border-rose-200 bg-rose-50 p-3 text-xs font-medium text-rose-700">
                  {adaptError}
                </div>
              )}

              {adaptMode === 'preview' && changes.length === 0 && !adaptLoading && (
                <div className="text-center py-8">
                  <div className="inline-flex h-12 w-12 items-center justify-center rounded-2xl bg-slate-100 text-slate-400">
                    <CheckCircle2 className="h-6 w-6" />
                  </div>
                  <h4 className="mt-3 font-semibold text-slate-900">Plan is on track</h4>
                  <p className="mt-1 text-sm text-slate-500">
                    No adaptation needed. Your current pace and completion patterns are healthy.
                  </p>
                </div>
              )}

              {adaptMode === 'preview' && changes.length > 0 && (
                <div className="space-y-4">
                  <div className="flex items-center justify-between text-sm">
                    <span className="font-semibold text-slate-700">
                      {changes.filter(c => c.type !== 0).length} change{changes.filter(c => c.type !== 0).length !== 1 ? 's' : ''} proposed
                    </span>
                    <span className="text-xs text-slate-500">
                      Based on your personal model signals
                    </span>
                  </div>

                  {changes.map((change, idx) => {
                    if (change.type === 0) return null; // Skip "NoChange"
                    const Icon = changeTypeIcons[change.type];
                    const colorClass = changeTypeColors[change.type];

                    return (
                      <div key={idx} className="rounded-2xl border border-slate-100 bg-slate-50/50 p-4">
                        <div className="flex items-start gap-3">
                          <div className={`flex h-8 w-8 shrink-0 items-center justify-center rounded-lg ${colorClass}`}>
                            <Icon className="h-4 w-4" />
                          </div>
                          <div className="flex-1 min-w-0">
                            <div className="flex items-center justify-between">
                              <h4 className="font-semibold text-slate-900">{change.summary}</h4>
                              <span className={`rounded-full px-2 py-0.5 text-[10px] font-medium uppercase ${colorClass}`}>
                                {PlanChangeTypeNames[change.type]}
                              </span>
                            </div>
                            <p className="mt-1 text-xs text-slate-600">{change.explanation}</p>
                            {change.affectedTaskIds.length > 0 && (
                              <div className="mt-2 flex flex-wrap gap-1.5">
                                {change.affectedTaskIds.slice(0, 5).map((taskId) => {
                                  const task = plans.flatMap(p => p.tasks).find(t => t.id === taskId);
                                  return task ? (
                                    <span key={taskId} className="rounded-md bg-white px-2 py-0.5 text-[10px] font-mono text-slate-600 border border-slate-200">
                                      #{task.order} {task.title}
                                    </span>
                                  ) : null;
                                })}
                                {change.affectedTaskIds.length > 5 && (
                                  <span className="rounded-md bg-slate-100 px-2 py-0.5 text-[10px] font-medium text-slate-500">
                                    +{change.affectedTaskIds.length - 5} more
                                  </span>
                                )}
                              </div>
                            )}
                          </div>
                        </div>
                      </div>
                    );
                  })}

                  <div className="mt-6 rounded-xl bg-indigo-50 p-4 border border-indigo-100">
                    <p className="text-xs text-indigo-800">
                      <strong>Transparency:</strong> These changes are calculated by the AdaptationEngine using only your recorded
                      behavioral signals (completions, skips, delays). No AI guesswork or external data.
                    </p>
                  </div>
                </div>
              )}

              {adaptMode === 'apply' && (
                <div className="text-center py-8">
                  <div className="inline-flex h-12 w-12 items-center justify-center rounded-2xl bg-indigo-50 text-indigo-600 animate-pulse">
                    <RefreshCw className="h-6 w-6 animate-spin" />
                  </div>
                  <h4 className="mt-3 font-semibold text-slate-900">Applying changes...</h4>
                  <p className="mt-1 text-sm text-slate-500">Updating plan tasks and version</p>
                </div>
              )}
            </div>

            {adaptMode === 'preview' && changes.length > 0 && (
              <div className="flex items-center justify-end gap-3 border-t border-slate-100 p-5">
                <button
                  onClick={handleAdaptCancel}
                  className="rounded-xl px-4 py-2 text-sm font-semibold text-slate-600 hover:bg-slate-100 transition-colors"
                >
                  Cancel
                </button>
                <button
                  onClick={handleAdaptApply}
                  disabled={adaptLoading}
                  className="inline-flex items-center gap-2 rounded-xl bg-amber-600 px-5 py-2 text-sm font-semibold text-white shadow-xs hover:bg-amber-700 disabled:opacity-50 transition-colors"
                >
                  <Check className="h-4 w-4" />
                  Apply Adaptation
                </button>
              </div>
            )}

            {adaptMode === 'apply' && (
              <div className="flex items-center justify-center gap-3 border-t border-slate-100 p-5">
                <button
                  onClick={handleAdaptCancel}
                  className="inline-flex items-center gap-2 rounded-xl bg-indigo-600 px-5 py-2 text-sm font-semibold text-white hover:bg-indigo-700 transition-colors"
                >
                  <Check className="h-4 w-4" />
                  Done
                </button>
              </div>
            )}
          </div>
        </div>
      )}
    </div>
  );
}